# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
edition = { workspace = true }
homepage = { workspace = true }
name = "iceberg-catalog-hms"
rust-version = { workspace = true }
version = { workspace = true }

categories = ["database"]
description = "Apache Iceberg Hive Metastore Catalog Support"
keywords = ["iceberg", "hive", "catalog"]
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
hive_metastore = { workspace = true }
iceberg = { workspace = true }
pilota = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
volo-thrift = { workspace = true }

# Transitive dependencies below

# Some dependencies don't correctly specify a minimal version for their dependencies and will fail to build in minimal versions build.
# So we specify the version of these transitive dependencies here.
# They can be removed when the direct dependencies are updated.

# transitive dependencies of pilota/volo-thrift
faststr = { workspace = true }
linkedbytes = { workspace = true }
metainfo = { workspace = true }
motore-macros = { workspace = true }
volo = { workspace = true }

[dev-dependencies]
ctor = { workspace = true }
iceberg_test_utils = { path = "../../test_utils", features = ["tests"] }
port_scanner = { workspace = true }

[package.metadata.cargo-machete]
# These dependencies are added to ensure minimal dependency version
ignored = ["faststr", "linkedbytes", "metainfo", "volo", "motore-macros"]
